openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Login endpoint
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 20
      responses:
        '200':
          description: Successful login
        '400':
          description: Bad request, invalid input

  /auth/register:
    post:
      summary: Register endpoint
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                  maxLength: 20
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request, invalid input

  /auth/logout:
    post:
      summary: Logout endpoint
      tags:
        - Authentication
      responses:
        '200':
          description: Successful logout
        '401':
          description: Unauthorized

  /auth/delete:
    post:
      summary: Delete user endpoint
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: User deleted successfully
        '404':
          description: User not found
