# coding: utf-8

"""
    Authentication API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_auth_delete_post(self) -> None:
        """Test case for auth_delete_post

        Delete user endpoint
        """
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        Login endpoint
        """
        pass

    def test_auth_logout_post(self) -> None:
        """Test case for auth_logout_post

        Logout endpoint
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        Register endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
