# coding: utf-8

"""
    Authentication System API

    API for user authentication and management

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_auth_delete_delete(self) -> None:
        """Test case for auth_delete_delete

        Delete User
        """
        pass

    def test_auth_login_post(self) -> None:
        """Test case for auth_login_post

        Authenticate User
        """
        pass

    def test_auth_register_post(self) -> None:
        """Test case for auth_register_post

        Register User
        """
        pass


if __name__ == '__main__':
    unittest.main()
