apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-auth-app-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: falcon-auth-app-dev
  template:
    metadata:
      labels:
        app: falcon-auth-app-dev
    spec:
      containers:
      - name: falcon-auth-app-dev
        image: your-docker-registry/falcon-auth-app:dev
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 750m # 75% of a CPU core
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        env:
        - name: DEV_DB_HOST
          value: "localhost"
        - name: DEV_DB_PORT
          value: "5432"
        - name: DEV_DB_NAME
          value: "dev_database"
        - name: DEV_DB_USER
          value: "dev_user"
        - name: DEV_DB_PASSWORD
          value: "dev_password"
        - name: DEV_SERVER_NAME
          value: "localhost"
        - name: DEV_SERVER_PORT
          value: "8000"
        autoscale:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 75
        metrics:
          enabled: true
          path: /metrics
          port: 8000
          scheme: HTTP