apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-auth-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: falcon-auth-app-prod
  template:
    metadata:
      labels:
        app: falcon-auth-app-prod
    spec:
      containers:
      - name: falcon-auth-app-prod
        image: your-docker-registry/falcon-auth-app:prod
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 750m # 75% of a CPU core
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        env:
        - name: PROD_DB_HOST
          value: "prod_host"
        - name: PROD_DB_PORT
          value: "prod_port"
        - name: PROD_DB_NAME
          value: "prod_database"
        - name: PROD_DB_USER
          value: "prod_user"
        - name: PROD_DB_PASSWORD
          value: "prod_password"
        - name: PROD_SERVER_NAME
          value: "localhost"
        - name: PROD_SERVER_PORT
          value: "8000"
        autoscale:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 75
        metrics:
          enabled: true
          path: /metrics
          port: 8000
          scheme: HTTP